In [1]:
import pandas as pd
import numpy as np

In [7]:
sales_df = pd.read_csv(
    "../data/sales_data.csv",
    encoding="latin1"
)

In [8]:
housing_df = pd.read_csv(
    "../data/USA Housing Dataset.csv"
)

analysis of sales data

In [9]:
sales_df.head()

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
0,10107,30,95.70,2,2871.00,2/24/2003 0:00,Shipped,1,2,2003,...,897 Long Airport Avenue,NaN,NYC,NY,10022,USA,NaN,Yu,Kwai,Small
1,10121,34,81.35,5,2765.90,5/7/2003 0:00,Shipped,2,5,2003,...,59 rue de l'Abbaye,NaN,Reims,NaN,51100,France,EMEA,Henriot,Paul,Small
2,10134,41,94.74,2,3884.34,7/1/2003 0:00,Shipped,3,7,2003,...,27 rue du Colonel Pierre Avia,NaN,Paris,NaN,75508,France,EMEA,Da Cunha,Daniel,Medium
3,10145,45,83.26,6,3746.70,8/25/2003 0:00,Shipped,3,8,2003,...,78934 Hillside Dr.,NaN,Pasadena,CA,90003,USA,NaN,Young,Julie,Medium
4,10159,49,100.00,14,5205.27,10/10/2003 0:00,Shipped,4,10,2003,...,7734 Strong St.,NaN,San Francisco,CA,NaN,USA,NaN,Brown,Julie,Medium

In [10]:
sales_df["SALES"].sum()

np.float64(10032628.85)

In [11]:
sales_df["SALES"].mean()

np.float64(3553.889071909316)

In [12]:
sales_df["SALES"].max()

14082.8

In [13]:
sales_df.sort_values(
    by="SALES",
    ascending=False
).head(10)

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
598,10407,76,100.0,2,14082.8,4/22/2005 0:00,On Hold,2,4,2005,...,3086 Ingle Ln.,NaN,San Jose,CA,94217,USA,NaN,Frick,Sue,Large
744,10322,50,100.0,6,12536.5,11/4/2004 0:00,Shipped,4,11,2004,...,2304 Long Airport Avenue,NaN,Nashua,NH,62005,USA,NaN,Young,Valarie,Large
53,10424,50,100.0,6,12001.0,5/31/2005 0:00,In Process,2,5,2005,...,"C/ Moralzarzal, 86",NaN,Madrid,NaN,28034,Spain,EMEA,Freyre,Diego,Large
1062,10412,60,100.0,9,11887.8,5/3/2005 0:00,Shipped,2,5,2005,...,"C/ Moralzarzal, 86",NaN,Madrid,NaN,28034,Spain,EMEA,Freyre,Diego,Large
104,10403,66,100.0,9,11886.6,4/8/2005 0:00,Shipped,2,4,2005,...,Berkeley Gardens 12 Brewery,NaN,Liverpool,NaN,WX1 6LT,UK,EMEA,Devon,Elizabeth,Large
1995,10405,76,100.0,3,11739.7,4/14/2005 0:00,Shipped,2,4,2005,...,"24, place Kluber",NaN,Strasbourg,NaN,67000,France,EMEA,Citeaux,Frederique,Large
44,10312,48,100.0,3,11623.7,10/21/2004 0:00,Shipped,4,10,2004,...,5677 Strong St.,NaN,San Rafael,CA,97562,USA,NaN,Nelson,Valarie,Large
1133,10333,46,100.0,2,11336.7,11/18/2004 0:00,Shipped,4,11,2004,...,5557 North Pendale Street,NaN,San Francisco,CA,NaN,USA,NaN,Murphy,Julie,Large
188,10127,46,100.0,2,11279.2,6/3/2003 0:00,Shipped,2,6,2003,...,4092 Furth Circle,Suite 400,NYC,NY,10022,USA,NaN,Young,Jeff,Large
30,10150,45,100.0,8,10993.5,9/19/2003 0:00,Shipped,3,9,2003,...,"Bronz Sok., Bronz Apt. 3/6 Tesvikiye",NaN,Singapore,NaN,79903,Singapore,Japan,Natividad,Eric,Large

In [14]:
sales_df.groupby(
    "PRODUCTLINE"
)["SALES"].sum()

PRODUCTLINE
Classic Cars        3919615.66
Motorcycles         1166388.34
Planes               975003.57
Ships                714437.13
Trains               226243.47
Trucks and Buses    1127789.84
Vintage Cars        1903150.84
Name: SALES, dtype: float64

In [15]:
sales_df.groupby(
    "COUNTRY"
)["SALES"].sum().sort_values(
    ascending=False
)

COUNTRY
USA            3627982.83
Spain          1215686.92
France         1110916.52
Australia       630623.10
UK              478880.46
Italy           374674.31
Finland         329581.91
Norway          307463.70
Singapore       288488.41
Denmark         245637.15
Canada          224078.56
Germany         220472.09
Sweden          210014.21
Austria         202062.53
Japan           188167.81
Switzerland     117713.56
Belgium         108412.62
Philippines      94015.73
Ireland          57756.43
Name: SALES, dtype: float64

In [16]:
sales_df["STATUS"].value_counts()

STATUS
Shipped       2617
Cancelled       60
Resolved        47
On Hold         44
In Process      41
Disputed        14
Name: count, dtype: int64

In [17]:
sales_df.groupby(
    "PRODUCTLINE"
)["SALES"].mean()

PRODUCTLINE
Classic Cars        4053.377104
Motorcycles         3523.831843
Planes              3186.286176
Ships               3053.150128
Trains              2938.226883
Trucks and Buses    3746.810100
Vintage Cars        3135.339110
Name: SALES, dtype: float64

In [18]:
sales_df.sort_values(
    by="PRICEEACH",
    ascending=False
).head()

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
842,10244,43,100.0,8,5950.34,4/29/2004 0:00,Shipped,2,4,2004,...,"C/ Moralzarzal, 86",NaN,Madrid,NaN,28034,Spain,EMEA,Freyre,Diego,Medium
1021,10151,21,100.0,7,3734.01,9/21/2003 0:00,Shipped,3,9,2003,...,Torikatu 38,NaN,Oulu,NaN,90110,Finland,EMEA,Koskitalo,Pirkko,Medium
1041,10278,42,100.0,7,6401.22,8/6/2004 0:00,Shipped,3,8,2004,...,8489 Strong St.,NaN,Las Vegas,NV,83030,USA,NaN,King,Sue,Medium
1040,10271,20,100.0,9,3928.60,7/20/2004 0:00,Shipped,3,7,2004,...,5677 Strong St.,NaN,San Rafael,CA,97562,USA,NaN,Nelson,Valarie,Medium
1039,10266,29,100.0,7,4812.55,7/6/2004 0:00,Shipped,3,7,2004,...,Strada Provinciale 124,NaN,Reggio Emilia,NaN,42100,Italy,EMEA,Moroni,Maurizio,Medium

In [19]:
sales_df["Revenue_Per_Item"] = (
    sales_df["SALES"] /
    sales_df["QUANTITYORDERED"]
)

sales_df.head()

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE,Revenue_Per_Item
0,10107,30,95.70,2,2871.00,2/24/2003 0:00,Shipped,1,2,2003,...,NaN,NYC,NY,10022,USA,NaN,Yu,Kwai,Small,95.70
1,10121,34,81.35,5,2765.90,5/7/2003 0:00,Shipped,2,5,2003,...,NaN,Reims,NaN,51100,France,EMEA,Henriot,Paul,Small,81.35
2,10134,41,94.74,2,3884.34,7/1/2003 0:00,Shipped,3,7,2003,...,NaN,Paris,NaN,75508,France,EMEA,Da Cunha,Daniel,Medium,94.74
3,10145,45,83.26,6,3746.70,8/25/2003 0:00,Shipped,3,8,2003,...,NaN,Pasadena,CA,90003,USA,NaN,Young,Julie,Medium,83.26
4,10159,49,100.00,14,5205.27,10/10/2003 0:00,Shipped,4,10,2003,...,NaN,San Francisco,CA,NaN,USA,NaN,Brown,Julie,Medium,106.23

analysis using housing dataset

In [20]:
housing_df.head()

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,street,city,statezip,country
0,2014-05-09 00:00:00,376000.0,3.0,2.00,1340,1384,3.0,0,0,3,1340,0,2008,0,9245-9249 Fremont Ave N,Seattle,WA 98103,USA
1,2014-05-09 00:00:00,800000.0,4.0,3.25,3540,159430,2.0,0,0,3,3540,0,2007,0,33001 NE 24th St,Carnation,WA 98014,USA
2,2014-05-09 00:00:00,2238888.0,5.0,6.50,7270,130017,2.0,0,0,3,6420,850,2010,0,7070 270th Pl SE,Issaquah,WA 98029,USA
3,2014-05-09 00:00:00,324000.0,3.0,2.25,998,904,2.0,0,0,3,798,200,2007,0,820 NW 95th St,Seattle,WA 98117,USA
4,2014-05-10 00:00:00,549900.0,5.0,2.75,3060,7015,1.0,0,0,5,1600,1460,1979,0,10834 31st Ave SW,Seattle,WA 98146,USA

In [22]:
housing_df.columns

Index(['date', 'price', 'bedrooms', 'bathrooms', 'sqft_living', 'sqft_lot',
       'floors', 'waterfront', 'view', 'condition', 'sqft_above',
       'sqft_basement', 'yr_built', 'yr_renovated', 'street', 'city',
       'statezip', 'country'],
      dtype='object')

In [23]:
housing_df["price"].mean()

np.float64(553062.8772890784)

In [24]:
##high price
housing_df["price"].max()

26590000.0

In [25]:
##low price
housing_df["price"].min()

0.0

In [26]:
##expensive house
housing_df.sort_values(
    by="price",
    ascending=False
).head(10)

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,street,city,statezip,country
3890,2014-07-03 00:00:00,26590000.0,3.0,2.00,1180,7793,1.0,0,0,4,1180,0,1992,0,12005 SE 219th Ct,Kent,WA 98031,USA
3886,2014-06-23 00:00:00,12899000.0,3.0,2.50,2190,11394,1.0,0,0,3,1550,640,1956,2001,5426 40th Ave W,Seattle,WA 98199,USA
1826,2014-06-11 00:00:00,7062500.0,5.0,4.50,10040,37325,2.0,1,2,3,7680,2360,1940,2001,4442 95th Ave NE,Bellevue,WA 98004,USA
2194,2014-06-17 00:00:00,4668000.0,5.0,6.75,9640,13068,1.0,1,4,3,4820,4820,1983,2009,5044 Butterworth Rd,Mercer Island,WA 98040,USA
2301,2014-06-18 00:00:00,4489000.0,4.0,3.00,6430,27517,2.0,0,0,3,6430,0,2001,0,1149-1199 91st Ave NE,Bellevue,WA 98004,USA
3269,2014-07-01 00:00:00,3800000.0,5.0,5.50,7050,42840,1.0,0,2,4,4320,2730,1978,2000,1365 91st Ave NE,Clyde Hill,WA 98004,USA
1177,2014-05-30 00:00:00,3710000.0,4.0,3.50,5550,28078,2.0,0,2,4,3350,2200,2000,0,3222 78th Pl NE,Medina,WA 98039,USA
1107,2014-05-29 00:00:00,3100000.0,6.0,4.25,6980,15682,3.0,0,4,4,5330,1650,1999,0,5243 Forest Ave SE,Mercer Island,WA 98040,USA
2312,2014-06-18 00:00:00,3000000.0,4.0,4.25,4850,12445,2.0,1,4,5,3850,1000,1989,0,11031 Champagne Point Rd NE,Kirkland,WA 98034,USA
1868,2014-06-11 00:00:00,2888000.0,5.0,6.25,8670,64033,2.0,0,4,3,6120,2550,1965,2003,1291 NW Elford Dr,Seattle,WA 98177,USA

In [28]:
##houses by city
housing_df["city"].value_counts()

city
Seattle               1415
Renton                 261
Bellevue               260
Redmond                209
Kent                   167
Kirkland               166
Auburn                 162
Issaquah               162
Sammamish              158
Federal Way            131
Shoreline              112
Woodinville            103
Maple Valley            90
Mercer Island           81
Snoqualmie              65
Burien                  64
Kenmore                 58
Des Moines              52
North Bend              45
Covington               39
Duvall                  39
Lake Forest Park        33
Newcastle               31
Bothell                 30
SeaTac                  29
Vashon                  28
Tukwila                 28
Enumclaw                28
Carnation               18
Normandy Park           16
Medina                  11
Clyde Hill              10
Fall City                9
Black Diamond            7
Pacific                  6
Yarrow Point             4
Ravensdale               4
Preston                  2
Milton                   2
Skykomish                2
Snoqualmie Pass          1
Beaux Arts Village       1
Algona                   1
Name: count, dtype: int64

In [29]:
##avg price by city
housing_df.groupby(
    "city"
)["price"].mean().sort_values(
    ascending=False
)

city
Medina                2.046559e+06
Clyde Hill            1.343140e+06
Yarrow Point          1.194838e+06
Mercer Island         1.111306e+06
Bellevue              8.616365e+05
Fall City             7.788333e+05
Beaux Arts Village    7.450000e+05
Sammamish             6.777309e+05
Newcastle             6.731424e+05
Redmond               6.629162e+05
Kirkland              6.581939e+05
Woodinville           6.068818e+05
Issaquah              5.999501e+05
Seattle               5.776812e+05
Preston               5.624500e+05
Ravensdale            5.571250e+05
Snoqualmie            5.399027e+05
Carnation             5.300857e+05
Snoqualmie Pass       5.250000e+05
Normandy Park         5.044859e+05
Vashon                4.803268e+05
Bothell               4.796694e+05
Kent                  4.538641e+05
Lake Forest Park      4.417303e+05
Kenmore               4.407449e+05
Shoreline             4.196590e+05
Duvall                4.084065e+05
North Bend            4.057732e+05
Renton                3.711870e+05
Black Diamond         3.669286e+05
Burien                3.472249e+05
Maple Valley          3.371938e+05
Tukwila               3.111219e+05
Des Moines            3.088023e+05
Enumclaw              3.076146e+05
Covington             3.019207e+05
Auburn                2.966572e+05
Federal Way           2.878132e+05
Milton                2.850000e+05
Skykomish             2.825000e+05
SeaTac                2.452906e+05
Pacific               2.252333e+05
Algona                1.964400e+05
Name: price, dtype: float64

Feature engineering

In [30]:
##price per sq feet

housing_df["price_per_sqft"] = (
    housing_df["price"] /
    housing_df["sqft_living"]
)

housing_df.head()

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,street,city,statezip,country,price_per_sqft
0,2014-05-09 00:00:00,376000.0,3.0,2.00,1340,1384,3.0,0,0,3,1340,0,2008,0,9245-9249 Fremont Ave N,Seattle,WA 98103,USA,280.597015
1,2014-05-09 00:00:00,800000.0,4.0,3.25,3540,159430,2.0,0,0,3,3540,0,2007,0,33001 NE 24th St,Carnation,WA 98014,USA,225.988701
2,2014-05-09 00:00:00,2238888.0,5.0,6.50,7270,130017,2.0,0,0,3,6420,850,2010,0,7070 270th Pl SE,Issaquah,WA 98029,USA,307.962586
3,2014-05-09 00:00:00,324000.0,3.0,2.25,998,904,2.0,0,0,3,798,200,2007,0,820 NW 95th St,Seattle,WA 98117,USA,324.649299
4,2014-05-10 00:00:00,549900.0,5.0,2.75,3060,7015,1.0,0,0,5,1600,1460,1979,0,10834 31st Ave SW,Seattle,WA 98146,USA,179.705882

In [31]:
##correlation
housing_df.corr(
    numeric_only=True
)

,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,price_per_sqft
price,1.000000,0.188765,0.317785,0.418528,0.045964,0.143180,0.131401,0.217553,0.030327,0.355214,0.204066,0.027067,-0.028272,0.828392
bedrooms,0.188765,1.000000,0.542549,0.590110,0.065747,0.178908,-0.001286,0.105512,0.016503,0.478124,0.329862,0.153514,-0.069439,-0.070139
bathrooms,0.317785,0.542549,1.000000,0.760353,0.097497,0.487462,0.080152,0.210590,-0.123024,0.687679,0.292170,0.470814,-0.221307,-0.030152
sqft_living,0.418528,0.590110,0.760353,1.000000,0.194226,0.345130,0.126157,0.308098,-0.069315,0.874881,0.439053,0.296545,-0.124646,-0.046797
sqft_lot,0.045964,0.065747,0.097497,0.194226,1.000000,-0.001113,0.019229,0.071264,0.012016,0.203190,0.023567,0.047224,-0.020308,-0.025763
floors,0.143180,0.178908,0.487462,0.345130,-0.001113,1.000000,0.021278,0.030604,-0.275212,0.524777,-0.261826,0.470139,-0.234445,-0.012364
waterfront,0.131401,-0.001286,0.080152,0.126157,0.019229,0.021278,1.000000,0.359237,0.004027,0.081076,0.109736,-0.031891,0.014030,0.031131
view,0.217553,0.105512,0.210590,0.308098,0.071264,0.030604,0.359237,1.000000,0.064440,0.167270,0.325002,-0.067859,0.028837,0.038979
condition,0.030327,0.016503,-0.123024,-0.069315,0.012016,-0.275212,0.004027,0.064440,1.000000,-0.183599,0.197656,-0.400394,-0.187971,0.046726
sqft_above,0.355214,0.478124,0.687679,0.874881,0.203190,0.524777,0.081076,0.167270,-0.183599,1.000000,-0.051039,0.416525,-0.163368,-0.043246
sqft_basement,0.204066,0.329862,0.292170,0.439053,0.023567,-0.261826,0.109736,0.325002,0.197656,-0.051039,1.000000,-0.161197,0.046034,-0.016272
yr_built,0.027067,0.153514,0.470814,0.296545,0.047224,0.470139,-0.031891,-0.067859,-0.400394,0.416525,-0.161197,1.000000,-0.321915,-0.072142
yr_renovated,-0.028272,-0.069439,-0.221307,-0.124646,-0.020308,-0.234445,0.014030,0.028837,-0.187971,-0.163368,0.046034,-0.321915,1.000000,0.014541
price_per_sqft,0.828392,-0.070139,-0.030152,-0.046797,-0.025763,-0.012364,0.031131,0.038979,0.046726,-0.043246,-0.016272,-0.072142,0.014541,1.000000