In [83]:
import numpy as np
import pandas as pd

In [84]:
sales_df = pd.read_csv(
    "../data/sales_data.csv",
    encoding="latin1"
)
sales_df.head(5)##printing top 5 records

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
0,10107,30,95.70,2,2871.00,2/24/2003 0:00,Shipped,1,2,2003,...,897 Long Airport Avenue,NaN,NYC,NY,10022,USA,NaN,Yu,Kwai,Small
1,10121,34,81.35,5,2765.90,5/7/2003 0:00,Shipped,2,5,2003,...,59 rue de l'Abbaye,NaN,Reims,NaN,51100,France,EMEA,Henriot,Paul,Small
2,10134,41,94.74,2,3884.34,7/1/2003 0:00,Shipped,3,7,2003,...,27 rue du Colonel Pierre Avia,NaN,Paris,NaN,75508,France,EMEA,Da Cunha,Daniel,Medium
3,10145,45,83.26,6,3746.70,8/25/2003 0:00,Shipped,3,8,2003,...,78934 Hillside Dr.,NaN,Pasadena,CA,90003,USA,NaN,Young,Julie,Medium
4,10159,49,100.00,14,5205.27,10/10/2003 0:00,Shipped,4,10,2003,...,7734 Strong St.,NaN,San Francisco,CA,NaN,USA,NaN,Brown,Julie,Medium

In [85]:
sales_df.tail(5)##printing last 5 records

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
2818,10350,20,100.00,15,2244.40,12/2/2004 0:00,Shipped,4,12,2004,...,"C/ Moralzarzal, 86",NaN,Madrid,NaN,28034,Spain,EMEA,Freyre,Diego,Small
2819,10373,29,100.00,1,3978.51,1/31/2005 0:00,Shipped,1,1,2005,...,Torikatu 38,NaN,Oulu,NaN,90110,Finland,EMEA,Koskitalo,Pirkko,Medium
2820,10386,43,100.00,4,5417.57,3/1/2005 0:00,Resolved,1,3,2005,...,"C/ Moralzarzal, 86",NaN,Madrid,NaN,28034,Spain,EMEA,Freyre,Diego,Medium
2821,10397,34,62.24,1,2116.16,3/28/2005 0:00,Shipped,1,3,2005,...,1 rue Alsace-Lorraine,NaN,Toulouse,NaN,31000,France,EMEA,Roulet,Annette,Small
2822,10414,47,65.52,9,3079.44,5/6/2005 0:00,On Hold,2,5,2005,...,8616 Spinnaker Dr.,NaN,Boston,MA,51003,USA,NaN,Yoshido,Juri,Medium

In [86]:
sales_df.describe()##count mean,sd,min,max,25%,75%

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,QTR_ID,MONTH_ID,YEAR_ID,MSRP
count,2823.000000,2823.000000,2823.000000,2823.000000,2823.000000,2823.000000,2823.000000,2823.00000,2823.000000
mean,10258.725115,35.092809,83.658544,6.466171,3553.889072,2.717676,7.092455,2003.81509,100.715551
std,92.085478,9.741443,20.174277,4.225841,1841.865106,1.203878,3.656633,0.69967,40.187912
min,10100.000000,6.000000,26.880000,1.000000,482.130000,1.000000,1.000000,2003.00000,33.000000
25%,10180.000000,27.000000,68.860000,3.000000,2203.430000,2.000000,4.000000,2003.00000,68.000000
50%,10262.000000,35.000000,95.700000,6.000000,3184.800000,3.000000,8.000000,2004.00000,99.000000
75%,10333.500000,43.000000,100.000000,9.000000,4508.000000,4.000000,11.000000,2004.00000,124.000000
max,10425.000000,97.000000,100.000000,18.000000,14082.800000,4.000000,12.000000,2005.00000,214.000000

In [87]:
##Handling missing values

sales_df.isnull()

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
0,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,True,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,True,False,True,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,True,False,True,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,True,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,True,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2818,False,False,False,False,False,False,False,False,False,False,...,False,True,False,True,False,False,False,False,False,False
2819,False,False,False,False,False,False,False,False,False,False,...,False,True,False,True,False,False,False,False,False,False
2820,False,False,False,False,False,False,False,False,False,False,...,False,True,False,True,False,False,False,False,False,False
2821,False,False,False,False,False,False,False,False,False,False,...,False,True,False,True,False,False,False,False,False,False
2822,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,True,False,False,False

In [88]:
sales_df.isnull().any(axis=1)##will return only the missing values as true others false

0       True
1       True
2       True
3       True
4       True
        ...
2818    True
2819    True
2820    True
2821    True
2822    True
Length: 2823, dtype: bool

In [89]:
sales_df.isnull().sum()#returns the sum of missing values in each columns

ORDERNUMBER            0
QUANTITYORDERED        0
PRICEEACH              0
ORDERLINENUMBER        0
SALES                  0
ORDERDATE              0
STATUS                 0
QTR_ID                 0
MONTH_ID               0
YEAR_ID                0
PRODUCTLINE            0
MSRP                   0
PRODUCTCODE            0
CUSTOMERNAME           0
PHONE                  0
ADDRESSLINE1           0
ADDRESSLINE2        2521
CITY                   0
STATE               1486
POSTALCODE            76
COUNTRY                0
TERRITORY           1074
CONTACTLASTNAME        0
CONTACTFIRSTNAME       0
DEALSIZE               0
dtype: int64

In [90]:
sales_df_filled = sales_df.fillna(0)# this will make all missing values as 0

In [91]:
# Fill missing values in text columns

sales_df['ADDRESSLINE2'] = sales_df['ADDRESSLINE2'].fillna('Unknown')

sales_df['STATE'] = sales_df['STATE'].fillna('Not Available')

sales_df['POSTALCODE'] = sales_df['POSTALCODE'].fillna('00000')

sales_df['TERRITORY'] = sales_df['TERRITORY'].fillna('Not Specified')

In [92]:
sales_df.isnull().sum()

ORDERNUMBER         0
QUANTITYORDERED     0
PRICEEACH           0
ORDERLINENUMBER     0
SALES               0
ORDERDATE           0
STATUS              0
QTR_ID              0
MONTH_ID            0
YEAR_ID             0
PRODUCTLINE         0
MSRP                0
PRODUCTCODE         0
CUSTOMERNAME        0
PHONE               0
ADDRESSLINE1        0
ADDRESSLINE2        0
CITY                0
STATE               0
POSTALCODE          0
COUNTRY             0
TERRITORY           0
CONTACTLASTNAME     0
CONTACTFIRSTNAME    0
DEALSIZE            0
dtype: int64

In [93]:
titanic_df = pd.read_csv("../data/titanic.csv")

titanic_df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [94]:
##filling missing values with mean of column
titanic_df['age'] = titanic_df['age'].fillna(titanic_df['age'].mean())

In [95]:
titanic_df.isnull().sum()

survived         0
pclass           0
sex              0
age              0
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [96]:
##renaming columns
titanic_df=titanic_df.rename(columns = {'age': 'age of the person'})

In [97]:
##checking datatypes
titanic_df.dtypes

survived               int64
pclass                 int64
sex                   object
age of the person    float64
sibsp                  int64
parch                  int64
fare                 float64
embarked              object
class                 object
who                   object
adult_male              bool
deck                  object
embark_town           object
alive                 object
alone                   bool
dtype: object

In [98]:
##changing datatypes

titanic_df['age of the person']= titanic_df['age of the person'].fillna(titanic_df['age of the person'].mean()).astype(int)

In [99]:
titanic_df.dtypes

survived               int64
pclass                 int64
sex                   object
age of the person      int64
sibsp                  int64
parch                  int64
fare                 float64
embarked              object
class                 object
who                   object
adult_male              bool
deck                  object
embark_town           object
alive                 object
alone                   bool
dtype: object

In [100]:
##Data aggregating and grouping

##using mean
grouped_mean = sales_df.groupby('CITY')['SALES'].mean()
grouped_mean

CITY
Aaarhus         3725.761111
Allentown       3939.940000
Barcelona       3409.211304
Bergamo         2874.077500
Bergen          3849.664828
                   ...
Toulouse        3524.422000
Tsawassen       2870.571154
Vancouver       3419.950909
Versailles      3601.906667
White Plains    3290.615000
Name: SALES, Length: 73, dtype: float64

In [101]:
##using sum
grouped_sum = sales_df.groupby(['CITY','COUNTRY'])['SALES'].sum()
grouped_sum

CITY          COUNTRY
Aaarhus       Denmark    100595.55
Allentown     USA        122138.14
Barcelona     Spain       78411.86
Bergamo       Italy      137955.72
Bergen        Norway     111640.28
                           ...
Toulouse      France      70488.44
Tsawassen     Canada      74634.85
Vancouver     Canada      75238.92
Versailles    France      64834.32
White Plains  USA         85555.99
Name: SALES, Length: 73, dtype: float64

In [102]:
##aggregate multiple functions

grouped_agg= sales_df.groupby('CITY')['SALES'].agg(['mean','sum','count'])
grouped_agg

                     mean        sum  count
CITY
Aaarhus       3725.761111  100595.55     27
Allentown     3939.940000  122138.14     31
Barcelona     3409.211304   78411.86     23
Bergamo       2874.077500  137955.72     48
Bergen        3849.664828  111640.28     29
...                   ...        ...    ...
Toulouse      3524.422000   70488.44     20
Tsawassen     2870.571154   74634.85     26
Vancouver     3419.950909   75238.92     22
Versailles    3601.906667   64834.32     18
White Plains  3290.615000   85555.99     26

[73 rows x 3 columns]

In [103]:
##merging and joining dataframes

##creating df

df1 = pd.DataFrame({'key':['A','B','C'], 'value1' : [1,2,3]})
df2 = pd.DataFrame({'key':['A','B','D'], 'value1' : [4,5,6]})
print(df1)
print(df2)

  key  value1
0   A       1
1   B       2
2   C       3
  key  value1
0   A       4
1   B       5
2   D       6

In [104]:
##merging df on key columns

##INNER JOIN

pd.merge(df1,df2,on="key",how="inner")

  key  value1_x  value1_y
0   A         1         4
1   B         2         5

In [105]:
##OUTER join

pd.merge(df1,df2,on="key",how="outer")

  key  value1_x  value1_y
0   A       1.0       4.0
1   B       2.0       5.0
2   C       3.0       NaN
3   D       NaN       6.0

In [106]:
##LEFT OUTER JOIN

pd.merge(df1,df2,on="key",how="left")

  key  value1_x  value1_y
0   A         1       4.0
1   B         2       5.0
2   C         3       NaN

In [107]:
##RIGHT OUTER JOIN

pd.merge(df1,df2,on="key",how="right")

  key  value1_x  value1_y
0   A       1.0         4
1   B       2.0         5
2   D       NaN         6

In [108]:
##reading data from different sources

from io import StringIO
import pandas as pd
data = '[{"employee_name":"John","email":"john@gmail.com"}]'
df = pd.read_json(StringIO(data))
print(df)

  employee_name           email
0          John  john@gmail.com

In [109]:
#df to json
df.to_json()

'{"employee_name":{"0":"John"},"email":{"0":"john@gmail.com"}}'

In [110]:
##df to json using parameter
##using Index
df.to_json(orient = 'index')

'{"0":{"employee_name":"John","email":"john@gmail.com"}}'

In [111]:
##using record

df.to_json(orient='records')

'[{"employee_name":"John","email":"john@gmail.com"}]'

In [112]:
##Read data from URL

import pandas as pd

url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/tips.csv"

df = pd.read_csv(url)

print(df.head())

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [113]:
pip install lxml

Requirement already satisfied: lxml in c:\users\vasihnavee\anaconda3\lib\site-packages (5.3.0)
Note: you may need to restart the kernel to use updated packages.

In [114]:
pip install html5lib beautifulsoup4

Requirement already satisfied: html5lib in c:\users\vasihnavee\anaconda3\lib\site-packages (1.1)
Requirement already satisfied: beautifulsoup4 in c:\users\vasihnavee\anaconda3\lib\site-packages (4.13.5)
Requirement already satisfied: six>=1.9 in c:\users\vasihnavee\anaconda3\lib\site-packages (from html5lib) (1.17.0)
Requirement already satisfied: webencodings in c:\users\vasihnavee\anaconda3\lib\site-packages (from html5lib) (0.5.1)
Requirement already satisfied: soupsieve>1.2 in c:\users\vasihnavee\anaconda3\lib\site-packages (from beautifulsoup4) (2.5)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\users\vasihnavee\anaconda3\lib\site-packages (from beautifulsoup4) (4.15.0)
Note: you may need to restart the kernel to use updated packages.

In [115]:
import pandas as pd
url = "https://afd.calpoly.edu/web/sample-tables"
htmlread = pd.read_html(url)
htmlread[0]

,Description,Date,Location
0,Academic Senate Meeting,"May 25, 2205",Building 99 Room 1
1,Commencement Meeting,"December 15, 2205",Building 42 Room 10
2,Dean's Council,"February 1, 2206",Building 35 Room 5
3,Committee on Committees,"March 3, 2206",Building 1 Room 201
4,"Lorem ipsum dolor sit amet, consectetuer adipi...","Lorem ipsum dolor sit amet, consectetuer adipi...","Lorem ipsum dolor sit amet, consectetuer adipi..."
5,Lorem ipsum dolor,Lorem ipsum dolor,Lorem ipsum dolor

In [116]:
sales_df.columns

Index(['ORDERNUMBER', 'QUANTITYORDERED', 'PRICEEACH', 'ORDERLINENUMBER',
       'SALES', 'ORDERDATE', 'STATUS', 'QTR_ID', 'MONTH_ID', 'YEAR_ID',
       'PRODUCTLINE', 'MSRP', 'PRODUCTCODE', 'CUSTOMERNAME', 'PHONE',
       'ADDRESSLINE1', 'ADDRESSLINE2', 'CITY', 'STATE', 'POSTALCODE',
       'COUNTRY', 'TERRITORY', 'CONTACTLASTNAME', 'CONTACTFIRSTNAME',
       'DEALSIZE'],
      dtype='object')

In [117]:
##date time conversion

sales_df["ORDERDATE"] = pd.to_datetime(
    sales_df["ORDERDATE"]
)

sales_df["ORDERDATE"].head()

0   2003-02-24
1   2003-05-07
2   2003-07-01
3   2003-08-25
4   2003-10-10
Name: ORDERDATE, dtype: datetime64[ns]

In [118]:
sales_df["ORDERDATE"].dtype

dtype('<M8[ns]')

In [119]:
sales_df["Day"] = sales_df["ORDERDATE"].dt.day

In [120]:

sales_df["Weekday"] = sales_df["ORDERDATE"].dt.day_name()

In [121]:

sales_df["Month_Name"] = sales_df["ORDERDATE"].dt.month_name()

In [122]:
sales_df[
    ["ORDERDATE","Day","Weekday","Month_Name"]
].head()

   ORDERDATE  Day    Weekday Month_Name
0 2003-02-24   24     Monday   February
1 2003-05-07    7  Wednesday        May
2 2003-07-01    1    Tuesday       July
3 2003-08-25   25     Monday     August
4 2003-10-10   10     Friday    October

In [123]:
##feature engineering

sales_df["Revenue_Per_Item"] = (
    sales_df["SALES"] /
    sales_df["QUANTITYORDERED"]
)

sales_df[
    ["SALES",
     "QUANTITYORDERED",
     "Revenue_Per_Item"]
].head()

     SALES  QUANTITYORDERED  Revenue_Per_Item
0  2871.00               30             95.70
1  2765.90               34             81.35
2  3884.34               41             94.74
3  3746.70               45             83.26
4  5205.27               49            106.23

In [124]:
##duplicate handling

sales_df.duplicated().sum()

np.int64(0)

In [125]:
sales_df.duplicated().sum()

np.int64(0)

In [126]:
##outlier detection

Q1 = sales_df["SALES"].quantile(0.25)

Q3 = sales_df["SALES"].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR

upper = Q3 + 1.5 * IQR

outliers = sales_df[
    (sales_df["SALES"] < lower)
    |
    (sales_df["SALES"] > upper)
]

outliers.head()

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE,Day,Weekday,Month_Name,Revenue_Per_Item
30,10150,45,100.0,8,10993.50,2003-09-19,Shipped,3,9,2003,...,79903,Singapore,Japan,Natividad,Eric,Large,19,Friday,September,244.300000
32,10174,34,100.0,4,8014.82,2003-11-06,Shipped,4,11,2003,...,4101,Australia,APAC,Calaghan,Tony,Large,6,Thursday,November,235.730000
35,10206,47,100.0,6,9064.89,2003-12-05,Shipped,4,12,2003,...,V3F 2K1,Canada,Not Specified,Tannamuri,Yoshi,Large,5,Friday,December,192.870000
41,10280,34,100.0,2,8014.82,2004-08-17,Shipped,3,8,2004,...,10100,Italy,EMEA,Accorti,Paolo,Large,17,Tuesday,August,235.730000
43,10304,47,100.0,6,10172.70,2004-10-11,Shipped,4,10,2004,...,78000,France,EMEA,Tonini,Daniel,Large,11,Monday,October,216.440426